# Generated by Django 5.0.2 on 2024-02-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellectsoft_app', '0004_remove_client_user_remove_operator_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='client',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='intellectsoft_app.client'),
            preserve_default=False,
        ),
    ]
